sudo: required
services:
  - docker

before_install:
  - docker build -t pranavkojha/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pranav-ojha/docker-react npm run test

language: generic
